name = "InflationFunctions"
uuid = "3d0454e0-948f-4743-b998-4d73da99f8a8"
authors = ["Rodrigo Chang <rrcp777@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CPIDataBase = "bc2aee9a-d1f8-4cce-8750-9c1afc923989"

[compat]
CPIDataBase = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
